# Generated by Django 3.0.6 on 2020-05-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=20)),
                ('att_date', models.CharField(max_length=20)),
                ('att_day', models.CharField(max_length=20)),
                ('att_month', models.CharField(max_length=20)),
                ('att_year', models.CharField(max_length=20)),
                ('in_time', models.CharField(default='-', max_length=20)),
                ('out_time', models.CharField(default='-', max_length=20)),
                ('duration', models.CharField(default='-', max_length=20)),
                ('summary', models.CharField(default='-', max_length=5000)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
        migrations.CreateModel(
            name='StudentLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20)),
                ('log_id', models.CharField(max_length=20)),
                ('log_name', models.CharField(max_length=20)),
                ('log_date', models.CharField(max_length=20)),
                ('log_time', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student_logs',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('parent', models.CharField(max_length=20)),
                ('addr', models.CharField(max_length=150)),
                ('c_date', models.CharField(max_length=20)),
                ('c_time', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('class_id', models.CharField(max_length=50)),
                ('section_id', models.CharField(max_length=50)),
                ('emb', models.TextField(max_length=3000)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
